dist: trusty
sudo: required
language: java
jdk: oraclejdk8
services:
  - docker
env:
  - RELEASE_TAG="release-$TRAVIS_BUILD_NUMBER"

script:
  - ./gradlew clean test
  - ./gradlew build

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: spring-boot-ci-travis