dist: trusty
sudo: required
services: docker
env:
  - RELEASE_TAG="release-$TRAVIS_BUILD_NUMBER"
stages:
  - build
  - deploy
if: tag IS blank

jobs:
  include:
    - stage: build
      language: java
      jdk: oraclejdk8
      install: skip
      script:
        - ./gradlew clean build
      before_deploy:
        - git config --local user.name "Travis CI"
        - git config --local user.email "travis@example.com"
        - git tag -f $RELEASE_TAG
      deploy: github
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file:
          - "spring-boot-ci-travis/build/libs/spring-boot-ci-travis.jar"
        skip_cleanup: true

    - stage: deploy
      language: bash
      script:
        - echo "Downloading application $RELEASE_TAG"
      deploy:
        provider: heroku
        api_key: $HEROKU_API_KEY
        app: spring-boot-ci-travis